import { Card, CardDraft, Folder, WordSet } from "@/domain/library";
import { DuplicateStrategy, analyzeImport } from "@/domain/bulkImport";
import type { LibraryRepository } from "@/lib/repositories";
import { requireSupabaseClient } from "@/lib/supabase";

const fail = (error: { message: string } | null) => { if (error) throw new Error(error.message); };
const name = (value: string, label: string) => { const trimmed = value.trim(); if (!trimmed) throw new Error(`${label}を入力してください。`); return trimmed; };
const draft = (value: CardDraft) => { const english = value.english.trim(); const japanese = value.japanese.trim(); if (!english || !japanese) throw new Error("英語と日本語を入力してください。"); return { english, japanese, note: value.note.trim(), partOfSpeech: value.partOfSpeech.trim() }; };
const currentUser = async () => { const supabase = requireSupabaseClient(); const { data, error } = await supabase.auth.getUser(); fail(error); if (!data.user) throw new Error("クラウドモードを利用するにはログインが必要です。"); return { supabase, userId: data.user.id }; };
type Row = Record<string, unknown>;
const text = (row: Row, key: string) => String(row[key] ?? "");
const folderFrom = (row: Row): Folder => ({ id: text(row, "id"), name: text(row, "name"), createdAt: text(row, "created_at"), updatedAt: text(row, "updated_at") });
const setFrom = (row: Row): WordSet => ({ id: text(row, "id"), folderId: text(row, "folder_id"), name: text(row, "name"), createdAt: text(row, "created_at"), updatedAt: text(row, "updated_at") });
const cardFrom = (row: Row): Card => ({ id: text(row, "id"), setId: text(row, "set_id"), orderIndex: Number(row.order_index ?? 0), english: text(row, "english"), japanese: text(row, "japanese"), note: text(row, "note"), partOfSpeech: text(row, "part_of_speech"), createdAt: text(row, "created_at"), updatedAt: text(row, "updated_at") });

class SupabaseLibraryRepository implements LibraryRepository {
  async ensureInitialData() { /* Cloud mode intentionally starts empty; migration belongs to stage 3B. */ }
  async listFolders() { const { supabase } = await currentUser(); const { data, error } = await supabase.from("folders").select("*").order("sort_order").order("created_at"); fail(error); return (data ?? []).map(folderFrom); }
  async getFolder(id: string) { const { supabase } = await currentUser(); const { data, error } = await supabase.from("folders").select("*").eq("id", id).maybeSingle(); fail(error); return data ? folderFrom(data) : undefined; }
  async createFolder(value: string) { const { supabase, userId } = await currentUser(); const { data, error } = await supabase.from("folders").insert({ user_id: userId, name: name(value, "フォルダ名") }).select().single(); fail(error); return folderFrom(data); }
  async updateFolder(id: string, value: string) { const { supabase } = await currentUser(); const { data, error } = await supabase.from("folders").update({ name: name(value, "フォルダ名") }).eq("id", id).select().single(); fail(error); return folderFrom(data); }
  async deleteFolder(id: string) { const { supabase } = await currentUser(); const { error } = await supabase.from("folders").delete().eq("id", id); fail(error); }
  async listWordSets(folderId: string) { const { supabase } = await currentUser(); const { data, error } = await supabase.from("word_sets").select("*, cards(count)").eq("folder_id", folderId).order("sort_order").order("created_at"); fail(error); return ((data ?? []) as unknown as Row[]).map((row) => { const counts = row.cards as Array<{ count?: number }> | undefined; return { ...setFrom(row), cardCount: counts?.[0]?.count ?? 0 }; }); }
  async getWordSet(id: string) { const { supabase } = await currentUser(); const { data, error } = await supabase.from("word_sets").select("*").eq("id", id).maybeSingle(); fail(error); return data ? setFrom(data) : undefined; }
  async createWordSet(folderId: string, value: string) { const { supabase, userId } = await currentUser(); const { data, error } = await supabase.from("word_sets").insert({ user_id: userId, folder_id: folderId, name: name(value, "セット名") }).select().single(); fail(error); return setFrom(data); }
  async updateWordSet(id: string, value: string) { const { supabase } = await currentUser(); const { data, error } = await supabase.from("word_sets").update({ name: name(value, "セット名") }).eq("id", id).select().single(); fail(error); return setFrom(data); }
  async duplicateWordSet(id: string) { const original = await this.getWordSet(id); if (!original) throw new Error("セットが見つかりません。"); const copy = await this.createWordSet(original.folderId, `${original.name} のコピー`); const cards = await this.listCards(id); await this.bulkImportCards(copy.id, cards.map(({ english, japanese, note, partOfSpeech }) => ({ english, japanese, note, partOfSpeech })), "allow"); return copy; }
  async deleteWordSet(id: string) { const { supabase } = await currentUser(); const { error } = await supabase.from("word_sets").delete().eq("id", id); fail(error); }
  async listCards(setId: string, query = "") { const { supabase } = await currentUser(); let request = supabase.from("cards").select("*").eq("set_id", setId).order("order_index"); if (query.trim()) request = request.or(`english.ilike.%${query.trim()}%,japanese.ilike.%${query.trim()}%`); const { data, error } = await request; fail(error); return (data ?? []).map(cardFrom); }
  async getCard(id: string) { const { supabase } = await currentUser(); const { data, error } = await supabase.from("cards").select("*").eq("id", id).maybeSingle(); fail(error); return data ? cardFrom(data) : undefined; }
  async createCard(setId: string, value: CardDraft) { const { supabase, userId } = await currentUser(); const existing = await this.listCards(setId); const d = draft(value); const { data, error } = await supabase.from("cards").insert({ user_id: userId, set_id: setId, order_index: existing.length + 1, english: d.english, japanese: d.japanese, note: d.note, part_of_speech: d.partOfSpeech }).select().single(); fail(error); return cardFrom(data); }
  async updateCard(id: string, value: CardDraft) { const { supabase } = await currentUser(); const d = draft(value); const { data, error } = await supabase.from("cards").update({ english: d.english, japanese: d.japanese, note: d.note, part_of_speech: d.partOfSpeech }).eq("id", id).select().single(); fail(error); return cardFrom(data); }
  async deleteCard(id: string) { const card = await this.getCard(id); if (!card) return; const { supabase } = await currentUser(); const { error } = await supabase.from("cards").delete().eq("id", id); fail(error); const rest = await this.listCards(card.setId); await Promise.all(rest.map((item, index) => supabase.from("cards").update({ order_index: index + 1 }).eq("id", item.id))); }
  async moveCard(setId: string, cardId: string, direction: "up" | "down") { const cards = await this.listCards(setId); const index = cards.findIndex((card) => card.id === cardId); const target = index + (direction === "up" ? -1 : 1); if (target < 0 || target >= cards.length) return; [cards[index], cards[target]] = [cards[target], cards[index]]; const { supabase } = await currentUser(); const results = await Promise.all(cards.map((card, order) => supabase.from("cards").update({ order_index: order + 1 }).eq("id", card.id))); results.forEach((result) => fail(result.error)); }
  async bulkImportCards(setId: string, values: CardDraft[], strategy: DuplicateStrategy) { const existing = await this.listCards(setId); const plan = analyzeImport(values, existing, strategy); if (plan.errors.length) throw new Error("入力エラーを修正してから登録してください。"); const { supabase, userId } = await currentUser(); const { data, error } = await supabase.rpc("bulk_import_cards", { p_set_id: setId, p_user_id: userId, p_creates: plan.creates.map(draft), p_updates: plan.updates.map((item) => ({ id: item.id, ...draft(item.draft) })) }); fail(error); const result = Array.isArray(data) ? data[0] : data; return { created: Number(result?.created_count ?? plan.creates.length), updated: Number(result?.updated_count ?? plan.updates.length), skipped: plan.skipped, total: Number(result?.total_count ?? existing.length + plan.creates.length) }; }
}

export const cloudLibraryRepository: LibraryRepository = new SupabaseLibraryRepository();
