"use client";

import { SpeechRate, SPEECH_RATES, SpeechSettings, selectEnglishVoice, speakEnglish } from "@/lib/speech";

export function SpeechSettingsPanel({ voices, loaded, supported, settings, onVoiceChange, onRateChange }: { voices: SpeechSynthesisVoice[]; loaded: boolean; supported: boolean; settings: SpeechSettings; onVoiceChange: (voiceURI: string) => void; onRateChange: (rate: SpeechRate) => void }) {
  const selected = selectEnglishVoice(voices, settings.voiceURI);
  const selectedVoiceURI = voices.some((voice) => voice.voiceURI === settings.voiceURI) ? settings.voiceURI : "";
  if (!supported) return <section className="speech-settings"><strong>英語音声</strong><p className="import-warning">このブラウザは音声読み上げに対応していません。学習機能はそのまま利用できます。</p></section>;
  return <section className="speech-settings"><strong>英語音声</strong><p className="speech-description">この端末で使える英語音声だけを表示します。選択内容はこの端末にのみ保存されます。</p><label>音声<select value={selectedVoiceURI} onChange={(event) => onVoiceChange(event.target.value)}><option value="">自動選択{selected ? `（${selected.name} / ${selected.lang}）` : ""}</option>{voices.map((voice) => <option key={voice.voiceURI} value={voice.voiceURI}>{voice.name} — {voice.lang}{voice.localService ? "（端末内）" : "（ネットワーク）"}{voice.default ? "（標準）" : ""}</option>)}</select></label>{loaded && !voices.length && <p className="import-warning">この端末で英語音声を確認できませんでした。端末の音声設定から英語音声を追加すると改善する可能性があります。</p>}<div className="speech-test"><button className="secondary" type="button" onClick={() => speakEnglish("Hello. This is a pronunciation test.", { ...settings, voiceURI: selectedVoiceURI }, voices)}>試聴する</button>{selected && <small>{selected.name} / {selected.lang}{selected.localService ? " / 端末内音声" : " / ネットワーク音声"}{selected.default ? " / 標準" : ""}</small>}</div><label>読み上げ速度<div className="delay-options">{SPEECH_RATES.map((rate) => <button type="button" key={rate} className={settings.rate === rate ? "selected" : ""} onClick={() => onRateChange(rate)}>{rate.toFixed(1)}</button>)}</div></label>{process.env.NODE_ENV === "development" && <p className="speech-debug">開発情報：英語音声 {voices.length} 件／選択：{selected ? `${selected.name} | ${selected.voiceURI} | ${selected.lang} | local=${selected.localService} | default=${selected.default}` : "自動（英語音声なし）"}</p>}</section>;
}
