"use client";

import { useEffect, useState } from "react";
import { ExistingCloudChoice, MigrationPreview, MigrationProgress, MigrationResult, migrateLocalData, previewMigration } from "@/lib/migration";

export function MigrationPanel({ onClose, onCompleted }: { onClose: () => void; onCompleted: () => void }) {
  const [preview, setPreview] = useState<MigrationPreview | null>(null); const [choice, setChoice] = useState<ExistingCloudChoice>("abort"); const [progress, setProgress] = useState<MigrationProgress | null>(null); const [result, setResult] = useState<MigrationResult | null>(null); const [error, setError] = useState("");
  useEffect(() => { void previewMigration().then(setPreview).catch((reason) => setError(reason instanceof Error ? reason.message : "移行情報を取得できませんでした。")); }, []);
  const begin = async () => { try { setError(""); const completed = await migrateLocalData(choice, setProgress); setResult(completed); onCompleted(); } catch (reason) { setError(reason instanceof Error ? reason.message : "移行に失敗しました。再試行できます。"); } };
  return <div className="modal-backdrop"><section className="migration-panel" role="dialog" aria-modal="true"><button className="panel-close" onClick={onClose}>×</button><p className="eyebrow">LOCAL TO CLOUD</p><h2>ローカルデータをクラウドへ移行</h2>{!preview ? <p>移行前のデータを検証しています…</p> : result ? <><p className="migration-success">移行が完了しました。クラウドモードを標準に設定しました。</p><dl><div><dt>フォルダ</dt><dd>{result.folders}件</dd></div><div><dt>セット</dt><dd>{result.wordSets}件</dd></div><div><dt>カード</dt><dd>{result.cards}件</dd></div><div><dt>完了日時</dt><dd>{new Date(result.completedAt).toLocaleString("ja-JP")}</dd></div></dl><p className="account-note">ローカルデータは、この端末内にバックアップとして残っています。</p><button className="primary" onClick={onClose}>閉じる</button></> : <><div className="migration-counts"><div><strong>ローカル</strong><span>フォルダ {preview.local.folders}件 / セット {preview.local.wordSets}件 / カード {preview.local.cards}件</span></div><div><strong>クラウド</strong><span>フォルダ {preview.cloud.folders}件 / セット {preview.cloud.wordSets}件 / カード {preview.cloud.cards}件</span></div></div>{preview.issues.length > 0 ? <div className="issue-list"><h3>移行できないエラー</h3>{preview.issues.map((issue) => <p key={`${issue.type}-${issue.id}`}>{issue.type}・{issue.name}（{issue.id}）：{issue.message}</p>)}</div> : <><p>移行予定：フォルダ {preview.local.folders}件、セット {preview.local.wordSets}件、カード {preview.local.cards}件</p>{(preview.cloud.folders || preview.cloud.wordSets || preview.cloud.cards) ? <label className="migration-choice">クラウド側に既存データがあります<select value={choice} onChange={(event) => setChoice(event.target.value as ExistingCloudChoice)}><option value="abort">移行を中止する</option><option value="add">ローカルにしかないデータを追加する</option><option value="update">同じIDのデータはローカルで更新する</option></select></label> : null}{progress && <p className="migration-progress">{progress.phase === "cards" ? "単語カード" : progress.phase}を移行中<br />{progress.completed} / {progress.total}件（{progress.total ? Math.round(progress.completed / progress.total * 100) : 0}%）</p>}<button className="primary" disabled={choice === "abort" && Boolean(preview.cloud.folders || preview.cloud.wordSets || preview.cloud.cards)} onClick={() => void begin()}>移行を開始</button></>}</>}{error && <p className="auth-error">{error}</p>}<button className="text-button" onClick={onClose}>キャンセル</button></section></div>;
}
